Update truckersmp-cli

diff --git a/truckersmp-cli b/truckersmp-cli
--- a/truckersmp-cli
+++ b/truckersmp-cli
@@ -32,12 +32,13 @@ done
 rm -f "./.checksums"
 
 if [ ! -z $errors ] && [ "$errors" = "1" ]; then
-    read -p "Some Errors Occured during the Downloading of Files, Continue or Try Again? [C/T]" $userinp1
-    if [ "$userinp1" = "C" ] || [ "$userinp1" = "c" ] || [ "$userinp1" = "Continue" ] || [ "$userinp1" = "continue" ]; then
+    zenity --question --icon-name=dialog-error --title "Truckers MP CLI" --text "Some Errors Occured during the Downloading of Files, Continue or Try Again?" --ok-label="Continue" --cancel-label="Try Again" --default-cancel
+    if [ $? = 0 ]; then
+        echo "Continuing..."
     else
         rm -rf "./truckersmp" "./files.json"
         #Relaunch to try again
-        "$0"
+        "$0" "$@"
         exit 0
     fi
 fi
