Try more legacy paths
Debian ❤

diff --git a/truckersmp-cli b/truckersmp-cli
--- a/truckersmp-cli
+++ b/truckersmp-cli
@@ -395,16 +395,32 @@ check_error() {
 
         # check for steam installation
         if [ "$proton" = true ] && ! [ -e "$steamdir/steam.sh" ]; then
-            print "Didn't found steam in $steamdir"
+            # Steam not found in $steamdir, let's try some other possible paths:
 
-            # debian based systems are using a special different location for steam
-            # let's try steams legacy path
-            if [ "$proton" = true ] && ! [ -e "$HOME/.steam/steam/steam.sh" ]; then
-                >&2 echo "Unable to locate the steam installation."
-                quit 1
-            else
+            # Legacy $HOME/.steam/steam should be a symlink to the steam installation:
+            if [ "$proton" = true ] && [ -e "$HOME/.steam/steam/steam.sh" ]; then
                 steamdir="$HOME/.steam/steam"
-                print "found steam in $steamdir"
+
+            # "This is a new installation, so use a distinct directory to avoid
+            # file collisions. Valve would use $XDG_DATA_HOME/Steam here.
+            # Debian uses a subdirectory of ~/.steam, to avoid having a mixture
+            # of XDG basedirs and traditional dotfiles in the same application."
+            # Debian uses $HOME/.steam/debian-installation
+            elif [ "$proton" = true ] && \
+                 [ -e "$HOME/.steam/debian-installation/steam.sh" ]; then
+                steamdir="$HOME/.steam/debian-installation"
+
+            # "The historical Debian behaviour has been to use ~/.steam as the
+            # installation directory in addition to using it as the control
+            # directory.This causes some file collisions, so we've moved away
+            # from that, but we can't easily disentangle this in existing
+            # installations."
+            # ~/.steam is the really old legacy path but can still be used
+            elif [ "$proton" = true ] && [ -e "$HOME/.steam/steam.sh" ]; then
+                steamdir="$HOME/.steam"
+            else
+                >&2 echo "Unable to locate your steam installation."
+                quit 1
             fi
         fi
     fi
